sudo: false

branches:
    only:
    - master
    - develop

language:
    - php
    - node_js

php:
    - '7.0'

node_js:
    - '6.0'

git:
    submodules: false

addons:
    ssh_known_hosts:

before_install:
    - echo "pantheon" >> $TRAVIS_BUILD_DIR/.git/info/exclude
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive wp-content/plugins/pantheon-hud

install:
    - npm install

script:
    - sh $TRAVIS_BUILD_DIR/deploy.sh
